'use client';
import { useEffect, useState } from 'react';
import { api } from '../../lib/api';
import { LeafletMap } from '../map/LeafletMapDynamic';
import { useFeedback } from '../../context/FeedbackContext';
const labels: Record<string,string> = { platform_commission_pct: 'Commission (%)', cancel_fee_after_grace: 'Cancellation fee (₹)', cancel_grace_period_sec: 'Free cancellation (seconds)', rush_surge_cap: 'Maximum rush multiplier', rush_surge_multiplier: 'Rush multiplier', night_charge_pct: 'Night surcharge (%)', max_dispatch_radius_meters: 'Dispatch radius (meters)', max_eta_minutes: 'Maximum estimated arrival (minutes)', worker_dispatch_timeout_sec: 'Offer timeout (seconds)' };
export function AdminOperations() {
  const { requestText, notify } = useFeedback();
  const [tab, setTab] = useState('Support'); const [tickets,setTickets] = useState<any[]>([]); const [customers,setCustomers] = useState<any[]>([]); const [workers,setWorkers] = useState<any[]>([]); const [settings,setSettings] = useState<Record<string,any>>({});
  const [message,setMessage] = useState(''); const [busy,setBusy] = useState(false);
  const load = async () => { setBusy(true); try { const result = await Promise.all([api.getSupportTickets(),api.getAdminCustomers(),api.getLiveWorkers(),api.getAdminSettings()]); for(const r of result) if(!r.success) throw new Error(r.message); setTickets(result[0].tickets);setCustomers(result[1].customers);setWorkers(result[2].workers);setSettings(result[3].settings); } catch(e:any){setMessage(e.message || 'Could not load operations.');} finally {setBusy(false);} };
  useEffect(()=>{void load();},[]);
  return <section className="bg-white p-5 border rounded-2xl space-y-4"><div className="flex flex-wrap gap-2">{['Support','Customers','Live professionals','Settings'].map(name=><button key={name} onClick={()=>setTab(name)} className={`px-4 py-2 rounded-xl text-sm font-bold ${tab===name?'bg-brand-600 text-white':'bg-slate-100'}`}>{name}</button>)}<button disabled={busy} onClick={load} className="border rounded-xl px-4">{busy?'Loading…':'Refresh'}</button></div>
    {message&&<p role="status" className="text-sm">{message}</p>}
    {tab==='Support'&&<div className="space-y-3">{!tickets.length&&<p>No contact messages yet.</p>}{tickets.map(ticket=><div key={ticket.id} className="border rounded-xl p-4 space-y-2"><p className="font-bold">{ticket.category} · {ticket.status}</p><p className="text-sm">{ticket.name} · {ticket.phone}</p><p className="whitespace-pre-wrap text-sm">{ticket.message}</p><p className="text-xs text-slate-500">Reference: {ticket.id}</p>{ticket.resolution&&<p className="text-sm">Resolution: {ticket.resolution}</p>}<button disabled={busy} className="text-brand-700 font-bold text-sm" onClick={async()=>{const resolution=await requestText({title:ticket.status==='OPEN'?'Resolve support ticket':'Reopen support ticket',message:'Save a clear follow-up note for the operations record.',defaultValue:ticket.resolution||'',placeholder:'Resolution / follow-up note',multiline:true,confirmLabel:ticket.status==='OPEN'?'Resolve ticket':'Reopen ticket'});if(resolution===null)return;setBusy(true);try{const r=await api.updateSupportTicket(ticket.id,ticket.status==='OPEN'?'RESOLVED':'OPEN',resolution);if(!r.success)throw new Error(r.message);notify('Support ticket updated.', 'success');await load();}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}}>{ticket.status==='OPEN'?'Resolve ticket':'Reopen ticket'}</button></div>)}</div>}
    {tab==='Customers'&&<div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr><th>Name</th><th>Phone</th><th>Bookings</th></tr></thead><tbody>{customers.map(c=><tr key={c.id} className="border-t"><td className="py-3">{c.name}</td><td>{c.phone}</td><td>{c._count.bookings}</td></tr>)}</tbody></table></div>}
    {tab==='Live professionals'&&<div className="space-y-3"><LeafletMap center={[28.6139,77.209]} zoom={11} markers={workers.filter(w=>w.lat!=null&&w.lng!=null).map(w=>({id:w.id,lat:w.lat,lng:w.lng,label:`${w.name} · ${w.isOnline?'online':'offline'}`}))} /><p className="text-xs text-slate-500">Last reported locations. Refresh for latest positions; stale locations are excluded from dispatch.</p>{workers.map(w=><p key={w.id} className="text-sm">{w.name} · {w.isOnline?'Online':'Offline'} · {w.isBusy?'On job':'Available'} · {w.lastLocationAt?new Date(w.lastLocationAt).toLocaleString():'No recent GPS'}</p>)}</div>}
    {tab==='Settings'&&<form className="grid sm:grid-cols-2 gap-4" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await api.updateAdminSettings(settings);if(!r.success)throw new Error(r.message);setMessage('Settings saved. Existing booking quotes are preserved.');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}}>{Object.entries(labels).map(([key,label])=><label key={key} className="text-sm">{label}<input type="number" step="any" min="0" required value={settings[key]??''} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})} className="block border rounded-xl p-2 mt-1 w-full" /></label>)}<button disabled={busy} className="p-3 rounded-xl bg-brand-600 text-white">Save settings</button></form>}
  </section>;
}
